include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    curly_braces_in_flow_control_structures: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"